<?php
require_once('./include/db_info.inc.php');
require_once('./include/setlang.php');
$sid=0;
if(isset($_GET['sid']))
{
    $sid=intval($_GET['sid']);
    $count=$database->count("vjudge_solution",["OR"=>["solution_id"=>$sid,"result"=>[0,14]]]);
    if($count>0)
    $result=$database->update("vjudge_solution",["runner_id"=>"0","result"=>"0"],["solution_id"=>$sid]);
}
?>
<script>
    history.go(-1);
</script>